version: '3'
services:
  db:
    image: postgres
    container_name: skill-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skill-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
